# TensorFlow Fundamentals


## Introduction to Tensors


We can imagine tensor as a multi-dimensional numerical representation (also referred to as n-dimensional, where n can be any number) of something(numbers, image, text or some other form of information or data)


* Numbers (using tensors to represent the price of houses)

* Image (using tensors to represent the pixels of an image)

* Text (using tensors to represent words)

* Some other form of information (or data) you want to represent with numbers.


Tensors are kind of like NumPy arrays. The main difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that tensors can be used on GPUs (graphical processing units)


The benefit of being able to run on GPUs and TPUs is faster computation.

Using GPUs and TPUs we can find the patterns in the numerical representations of data faster.


[list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/)



### A scalar is known as a rank 0 tensor. It has no dimensions

Tensors can have an unlimited range of dimensions

In [1]:
import tensorflow as tf
print(tf.__version__)


2.8.2


In [10]:
# create tensors with tf.constant()
scaler = tf.constant(10)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
# check the number of dimensions in tensor
scaler.ndim

0

In [9]:
# create a vector
vector = tf.constant([9, 8])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 8], dtype=int32)>

In [4]:
# check the dimensions of vector
vector.ndim

1

In [11]:
# create a matrix (has more than 1 dimensions)
matrix = tf.constant([
    [5, 0],
    [9, 4]
])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 0],
       [9, 4]], dtype=int32)>

In [12]:
matrix.ndim

2

In [15]:
# create another matrix
another_matrix = tf.constant([
        [5, 6],
        [1, 8],
        [5.0, 10.0]],
        dtype=tf.float16
)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 5.,  6.],
       [ 1.,  8.],
       [ 5., 10.]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [19]:
# Let's creat a tensor
tensor = tf.constant([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [20]:

tensor.ndim

3

**scalar**: a single number.
**vector**: a number with direction (e.g. wind speed with direction).
**matrix**: a 2-dimensional array of numbers.
**tensor**: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

-----


# Creating tensor with `tf.Variable()`


The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable() `are mutable (can be changed).

In [21]:

# create same tensor with tf.variable() as above
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [22]:
# Let's try change one the elements in changable tensor
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangable_tensor[0].assign(7) # we can't change constant value
unchangable_tensor

Most of the time, TensorFlow will automatically (when loading data or modelling data).(tf.Variable() or tf.constant())

# Random Tensors

Tensors of arbitary size which contain random numbers.

In [24]:
# create two random tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [25]:

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [26]:
# are they equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

-----

# Shuffling the order elements in  tensor

- **if we want to shuffle the data and make them in same order, we need to use both operational level and global level seed.**

### Global vs Operation Level Seed

`tf.random.set_seed(42)` sets the global seed, and the seed parameter in `tf.random.shuffle(seed=42)` sets the operation seed.


If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."



In [27]:
not_shuffle = tf.constant([[10, 7], [1, 2], [3, 4]])
not_shuffle.ndim

2

In [28]:
# shuffle our tensor
# we can see that shuffling make the first dimension shuffle
after_shuffled = tf.random.shuffle(not_shuffle)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 1,  2]], dtype=int32)>

In [29]:
after_shuffled = tf.random.shuffle(not_shuffle, seed=42)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 1,  2],
       [10,  7]], dtype=int32)>

In [30]:
tf.random.set_seed(42)
after_shuffled = tf.random.shuffle(not_shuffle)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [31]:
after_shuffled = tf.random.shuffle(not_shuffle)
after_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 1,  2]], dtype=int32)>

In [33]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
# tf.random.shuffle(not_shuffle)
tf.random.shuffle(not_shuffle, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 3,  4]], dtype=int32)>

In [34]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffle)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [36]:
tf1 = tf.constant([[3, 4], [5, 6], [1,2]])
tf1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

#### operation level random seed

In [37]:
tf.random.shuffle(tf1, seed=42) # operation level random seed
# we can see that this will produce randomly shuffled every time we re-run the line

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

#### global level random seed

In [38]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(tf1, seed=41)

# after setting global level random seed, we can see that no matter how many time we re-run this block of code, it doesn't change the seqeuence at all.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

# Creating tensors from NumPy arrays



In [39]:
# create a tensor of ones
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [40]:
# create a tensor of zeros
tf.zeros(shape=(3, 5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [41]:
tf.zeros([3, 5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

## Turn Numpy array to Tensor
The main difference between Numpy arrys and Tensors is that Tensors can be run on GPU computing.

In [44]:
# you can also turn Numpy array to tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [45]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [46]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [47]:
2 * 3 * 4

24

In [48]:
A = tf.constant(numpy_A, shape=(8, 3))
A

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

In [49]:
A.ndim

2

-----

#  Tensors Attributes / Shape, rank, size



- **Shape**: The length (number of elements) of each of the dimensions of a tensor. `tensor.shape`
- **Rank**: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. `tensor.ndim`
- **Axis or Dimension**: A particular dimension of a tensor. `tensor[0], tensor[:, 1]`
- **Size**: The total number of items in the tensor. `tf.size(tensor)`



In [51]:
# Create a rank 4 tensor (4 dimensions)
rank4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [52]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [53]:
rank4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [54]:
rank4_tensor.shape

TensorShape([2, 3, 4, 5])

In [55]:
rank4_tensor.ndim

4

In [56]:
tf.size(rank4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [57]:
2 * 3 * 4 * 5

120

## Get various attributes of tensors


In [58]:
# Get various attributes of tensors
print('DataType of every element: ', rank4_tensor.dtype)
print('Number of dimensions (rank): ', rank4_tensor.ndim)
print('Shape of tensor: ', rank4_tensor.shape)
print('Elements along the axis 0: ', rank4_tensor.shape[0]) # refer to the shape of the tensor and check the first index
print('Elements along the last axis: ', rank4_tensor.shape[-1])
print('Total elements in our tensor: ', tf.size(rank4_tensor))
print('Total elements in our tensor: ', tf.size(rank4_tensor).numpy()) # # .numpy() converts to NumPy array

DataType of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the axis 0:  2
Elements along the last axis:  5
Total elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total elements in our tensor:  120



# Indexing and Expanding Tensors

You can also index tensors just like Python lists.

In [61]:
somelist = [1, 2, 3, 4]
somelist[:2]

[1, 2]

In [62]:
# get the first 2 elements of each dimensions
rank4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [63]:

rank4_tensor.shape

TensorShape([2, 3, 4, 5])

In [64]:
# get the first element from each dimension , except for the final one
rank4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [65]:
rank4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [66]:
rank4_tensor[:1, :, :1, :1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [67]:
rank4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [68]:
rank4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [69]:
# create a rank2 tensor (2 dimensions)
rank2_tensor = tf.constant([[10, 7], 
                                      [3, 4]])
rank2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [70]:
rank2_tensor.shape, rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [71]:
# let's get last item of each row of our rank2 tensor
rank2_tensor[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [72]:
# if we want to add additional dimension
rank2_tensor[: , -1:]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[7],
       [4]], dtype=int32)>

## Add in extra dimension to our rank2tensor

means for every axis
There are 2 ways to do this.
+ tf.newaxis()
+ tf.expand_dims()

In [73]:
# Add in extra dimension to our rank2tensor
rank3_tensor = rank2_tensor[..., tf.newaxis] # same as [:, :, :, tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [74]:
# Alternative to tf.newaxis
tf.expand_dims(rank2_tensor, axis=-1) # -1 means expands to last axis

# so from (2,2) became (2,2,1) , new 1 dimension to last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [75]:
tf.expand_dims(rank2_tensor, axis=0)

# so from (2,2) became (1,2,2) , new 1 dimension to first axis or 0 - axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [76]:
tf.expand_dims(rank2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>


-----------

# Manipulating tensors with Basic Operations



## Basic operations
You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, +, -, *, /

In [78]:
# we can add tensors 
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [79]:
tensor # original tensor is unchanged.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [80]:
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [81]:
# multiplication
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 34],
       [26, 28]], dtype=int32)>

In [82]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [83]:
tensor / 7

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2.85714286, 2.42857143],
       [1.85714286, 2.        ]])>

In [84]:
# We can use tensorflow built in functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [85]:
tf.divide(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10. ,  8.5],
       [ 6.5,  7. ]])>

In [86]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [87]:
tf.add(tensor, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 22],
       [18, 19]], dtype=int32)>

In [88]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

--------

# Matrix mutliplication




In [89]:
# matrix multiplication in tensorflow
print(tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


In [90]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [91]:
tensor * tensor # element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [169, 196]], dtype=int32)>

In [92]:
left_tensor = tf.constant([[1, 2, 5], [7, 2, 1], [3, 3, 3]])
right_tensor = tf.constant([[3, 5], [6, 7], [1, 8]])

left_tensor, right_tensor

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [93]:
tf.matmul(left_tensor, right_tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

## Matrix multiplication with python operator @

In [94]:
left_tensor @ right_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [95]:
# create a tensor (3,2) 
X = tf.constant([[1,2], [3, 4], [5, 6]])

# create another (3, 2) tensor
Y = tf.constant([[7, 8], [9, 10], [11, 12]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [98]:
# try to matrix multiply tensors of same shape
X @ Y 

InvalidArgumentError: ignored

In [99]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

## Matrix Mulitplication (Reshape tensors)

In [100]:
X.shape, Y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [101]:
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [102]:
# change the shape of X
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [103]:
# change the shape of Y
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [104]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

## Matrix multiplication with Transpose




In [207]:
# can do the same with Transpose
# but we can see that the results are different from Transpose & Reshape
tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [208]:
# try matrix multiplication with Transpose
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

## The dot product

You can perform the `tf.matmul()` operation using `tf.tensordot()`


In [107]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [108]:
# perform dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [109]:
# perform matrix mulitplication between X and Y  (transpose)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [110]:
# perform matrix multiplication between X and Y (reshape)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

## Check the value of Y, reshape Y and transposed Y

In [111]:
# Check the value of Y, reshape Y and transposed Y
print('Normal Y: ', Y)
print('\n Y reshaped: ', tf.reshape(Y, shape=(2, 3)))
print('\n Y transposed: ', tf.transpose(Y))

Normal Y:  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)

 Y reshaped:  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

 Y transposed:  tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)



# Changing the datatype of a tensor

Sometimes we want to alter the default datatype of tensor. 


Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).


In [209]:
tf.__version__

'2.8.2'

In [210]:
# create a new tensor with default datatype (float 32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [211]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [212]:
# Change from float 32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

In [213]:
# change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E.dtype

tf.float32

In [214]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16.dtype

tf.float16

----

# Getting the absolute Value

`tf.abs()`

In [215]:
test = tf.constant([[-7, -9]])
test

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[-7, -9]], dtype=int32)>

In [216]:
tf.abs(test) # Get the absolute values

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[7, 9]], dtype=int32)>

# Aggregation Tensors

### Finding the min, max, mean, sum (aggregation)

**Aggregrating Tensors**: condensing them from multiple values down to a smaller amount of values.

In [217]:
import numpy as np

In [218]:
# create a random tensor with values between 0 and 100
sample = tf.constant(np.random.randint(0, 100, size=50))
sample

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([13, 59, 11, 82,  2, 69, 42,  5, 87, 27, 46, 98, 54, 19, 90, 12, 65,
       42, 93, 60, 68,  6, 26, 34, 60, 62, 75, 87, 54,  7, 74, 19,  2, 77,
       51, 83, 12,  2, 92, 68,  5, 35, 30, 77, 20, 99, 49, 74, 21, 79])>

In [219]:
# find the minimum
tf.reduce_min(sample)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [220]:
# find the maximum
tf.reduce_max(sample)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [221]:
# find the mean
tf.reduce_mean(sample)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [222]:
# find the sum
tf.reduce_sum(sample)

<tf.Tensor: shape=(), dtype=int64, numpy=2424>

In [223]:
import tensorflow_probability as tfp

In [224]:
# find the variance
tfp.stats.variance(sample)

<tf.Tensor: shape=(), dtype=int64, numpy=935>

In [225]:
tf.math.reduce_variance(tf.cast(sample, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=934.8095>

In [226]:
# find the standard deviation
tf.math.reduce_std(tf.cast(sample, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.574656>

# Finding the positional maximum and minimum

Finding the position a tensor where the maximum value occurs?


`tf.argmax()`  find the position of the minimum element in a given tensor.


`tf.argmin()`  find the position of the minimum element in a given tensor.

In [227]:
# create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [228]:
# Find the positional maximum, Position where maximum value is located
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [229]:
np.argmax(F)

42

In [230]:
# Index on our largest value position
# using that index, we can get the value of largest number
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [231]:
# Find the maximum value using reduce_max
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

All those values using different methods lined up.

In [232]:
# Check for equlity
# As those values are equal, we don't get any errors
assert(F[tf.argmax(F)]) == tf.reduce_max(F)

In [233]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [234]:
# find the minium position
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [235]:
# find the minimum value
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [236]:
# Find the maximum element position of F
print(f"The maximum value of F is at position: {tf.argmax(F).numpy()}") 
print(f"The maximum value of F is: {tf.reduce_max(F).numpy()}") 
print(f"Using tf.argmax() to index F, the maximum value of F is: {F[tf.argmax(F)].numpy()}")
print(f"Are the two max values the same (they should be)? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

The maximum value of F is at position: 42
The maximum value of F is: 0.967138409614563
Using tf.argmax() to index F, the maximum value of F is: 0.967138409614563
Are the two max values the same (they should be)? True


# Squeezing a tensor (removing dimensions)

If we need to remove single-dimensions from a tensor (dimensions with size 1), we can use `tf.squeeze()`.

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) - remove all dimensions of 1 from a tensor.

Example: in our following example, our tensor has so many 1 dimenions. So we can squeeze that to become into single dimension.


In [238]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [239]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [240]:
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

# One-hot encoding

`tf.one_hot()`

`depth` parameter (the level of one-hot encoding).

In [241]:
# create a list of indices
some_list = [0, 1, 2, 3] 

# one hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [147]:
# speicify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value='Yaeee', off_value="Nayyy")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yaeee', b'Nayyy', b'Nayyy', b'Nayyy'],
       [b'Nayyy', b'Yaeee', b'Nayyy', b'Nayyy'],
       [b'Nayyy', b'Nayyy', b'Yaeee', b'Nayyy'],
       [b'Nayyy', b'Nayyy', b'Nayyy', b'Yaeee']], dtype=object)>


# Squaring, log, square root

`tf.square()` - get the square of every value in a tensor. 

`tf.sqrt()` - get the squareroot of every value in a tensor (elements need to floats).

`tf.math.log()` - get the natural log of every value in a tensor (elements need to floats).

In [242]:
# create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [243]:
# Find the square
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [244]:
# Find square root (method require Non Integer values)
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [245]:
# Find the Log (method require Non Integer values)
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# .assign() & .add_assign()

`.assign()` - assign a different value to a particular index of a variable tensor.
`.add_assign()` - add to an existing value and reassign it at a particular index of a variable tensor.

In [247]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [248]:
# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [249]:
# The change happens in place (the last value is now 50, not 4)
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [250]:
# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [251]:
# Again, the change happens in place
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

In [252]:
# Subtract 2 to every element in I
I.assign_sub([2, 2, 2, 2, 2])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 8,  9, 10, 11, 58])>

In [253]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([ 8,  9, 10, 11, 58])>

#Tensors and NumPy


* `np.array()` - pass a tensor to convert to an ndarray (NumPy's main datatype).
* `tensor.numpy()` - call on a tensor to convert to an ndarray.

It makes tensors iterable as well as allows us any of NumPy's methods on tensors

In [254]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [255]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [256]:
# Convert tensor J to NumPy with .numpy()
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [257]:
J = tf.constant([3.])
J

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>

In [258]:
J.numpy()[0]

3.0

**By default tensors have `dtype=float32`, where as NumPy arrays have `dtype=float64`.**

This is because neural networks (usually built with TensorFlow) generally work very well with less precision (32-bit rather than 64-bit).

In [260]:
# Create a tensor from NumPy and from an array
numpy_J = tf.constant(np.array([3., 7., 10.])) # will be float64 (due to NumPy)
tensor_J = tf.constant([3., 7., 10.]) # will be float32 (due to being TensorFlow default)

# check the datatype of each ones
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

# Access to GPUs

`tf.config.list_physical_devices()`

In [261]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [262]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [263]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [264]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [265]:
#  finding info using`!nvidia-smi`.

!nvidia-smi

Sun Sep 11 18:48:29 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P0    28W /  70W |    994MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## `TensorFlow` automatically use `GPU` whenever possible.

# Using `@tf.function`

`@tf.function` - Python Decorator

decorators modify a function in one way or another.

`@tf.function` turns a Python function into a callable TensorFlow graph. If you've written a Python function, and you decorate it with `@tf.function`, when exporting this code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).


In [266]:
import numpy as np

In [267]:
# create a simple function
def function(x,y):
  return x+y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])>

In [268]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x,y):
  return x+y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])>

If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

--------

# Exercises


In [174]:
#import numpy
import numpy as np

# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
scalar = tf.constant(12)
vector = tf.constant([1, 2])
matrix = tf.constant([[1, 2], [3, 4]])
tensor = tf.random.Generator.from_seed(42)
tensor = tensor.normal(shape=(3, 2))

scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=12>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>)

In [175]:
# 2.Find the shape, rank and size of the tensors you created in 1
print('Shape of tensor: ', tensor.shape)
print('Rank (dimensions) of tensor: ', tensor.ndim)
print('Size of tensor: ', tf.size(tensor))

Shape of tensor:  (3, 2)
Rank (dimensions) of tensor:  2
Size of tensor:  tf.Tensor(6, shape=(), dtype=int32)


In [176]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor1 = tf.random.Generator.from_seed(42)
tensor1 = tensor1.normal(shape=(5, 300))

tensor2 = tf.constant(np.arange(1, 51, 1500), shape=(5, 300))

In [177]:
tensor1.shape, tensor2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [178]:
tf.reshape(tensor2, shape=(300, 5))

<tf.Tensor: shape=(300, 5), dtype=int64, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       ...,
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [179]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(tensor1, tf.cast(tf.reshape(tensor2, shape=(300, 5)), dtype=tf.float32))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-18.116056  , -18.116056  , -18.116056  , -18.116056  ,
        -18.116056  ],
       [-16.531065  , -16.531065  , -16.531065  , -16.531065  ,
        -16.531065  ],
       [  6.35018   ,   6.35018   ,   6.35018   ,   6.35018   ,
          6.35018   ],
       [-24.067091  , -24.067091  , -24.067091  , -24.067091  ,
        -24.067091  ],
       [  0.62193453,   0.62193453,   0.62193453,   0.62193453,
          0.62193453]], dtype=float32)>

In [180]:
# 5.Multiply the two tensors you created in 3 using dot product.
tf.tensordot(tensor1, tf.cast(tf.transpose(tensor2), dtype=tf.float32), axes=0)

<tf.Tensor: shape=(5, 300, 300, 5), dtype=float32, numpy=
array([[[[-0.7565803 , -0.7565803 , -0.7565803 , -0.7565803 ,
          -0.7565803 ],
         [-0.7565803 , -0.7565803 , -0.7565803 , -0.7565803 ,
          -0.7565803 ],
         [-0.7565803 , -0.7565803 , -0.7565803 , -0.7565803 ,
          -0.7565803 ],
         ...,
         [-0.7565803 , -0.7565803 , -0.7565803 , -0.7565803 ,
          -0.7565803 ],
         [-0.7565803 , -0.7565803 , -0.7565803 , -0.7565803 ,
          -0.7565803 ],
         [-0.7565803 , -0.7565803 , -0.7565803 , -0.7565803 ,
          -0.7565803 ]],

        [[-0.06854702, -0.06854702, -0.06854702, -0.06854702,
          -0.06854702],
         [-0.06854702, -0.06854702, -0.06854702, -0.06854702,
          -0.06854702],
         [-0.06854702, -0.06854702, -0.06854702, -0.06854702,
          -0.06854702],
         ...,
         [-0.06854702, -0.06854702, -0.06854702, -0.06854702,
          -0.06854702],
         [-0.06854702, -0.06854702, -0.06854702, -0.

In [181]:
# 6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor3 = tf.random.Generator.from_seed(42)
tensor3 = tensor3.uniform(shape=[224, 224, 3])
tensor3.shape

TensorShape([224, 224, 3])

In [182]:
224*224*3

150528

In [183]:
# 7.Find the min and max values of the tensor you created in 6.
tensor3_1D = tf.reshape(tensor3, shape=[150528])
tensor3_1D.shape

TensorShape([150528])

In [184]:
print('Minimum value: ', tensor3_1D[tf.argmin(tensor3_1D)])
print('Maximum value: ', tensor3_1D[tf.argmax(tensor3_1D)])

Minimum value:  tf.Tensor(4.053116e-06, shape=(), dtype=float32)
Maximum value:  tf.Tensor(0.99998736, shape=(), dtype=float32)


In [185]:
# 8.Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor4 = tf.constant(np.arange(0, 100, 150528), shape=[1, 224, 224, 3])
tensor4.shape

TensorShape([1, 224, 224, 3])

In [186]:
squeezed_tensor4 = tf.squeeze(tensor4)
squeezed_tensor4.shape

TensorShape([224, 224, 3])

In [187]:
# 9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor5 = tf.random.Generator.from_seed(42)
tensor5 = tensor5.uniform(shape=[10])
tensor5

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ,
       0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ],
      dtype=float32)>

In [188]:
print('Index of maxmimum value: ', tf.argmax(tensor5))
print('Maximum value: ', tf.argmax(tensor5))

Index of maxmimum value:  tf.Tensor(6, shape=(), dtype=int64)
Maximum value:  tf.Tensor(6, shape=(), dtype=int64)


In [189]:
tensor5 = tf.constant(np.arange(1, 11))
tensor5

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [190]:
print('Index of maxmimum value: ', tf.argmax(tensor5))
print('Maximum value: ', tf.argmax(tensor5))

Index of maxmimum value:  tf.Tensor(9, shape=(), dtype=int64)
Maximum value:  tf.Tensor(9, shape=(), dtype=int64)


In [191]:
# 10.One-hot encode the tensor you created in 9.
tf.one_hot(tensor5, depth=1)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [269]:
# quick Tutorial

import tensorflow as tf

In [270]:
# load and prepare the MNIST dataset
mnist = tf.keras.datasets.mnist

In [271]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((60000, 28, 28), (10000, 28, 28), (60000,), (10000,))

In [272]:
# scale the data
x_train = x_train / 255.0
x_test = x_test / 255.0

In [273]:
# Build the tf.keras.Sequential model by stacking layers. Choose an optimizer and loss function for training:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout

In [274]:
model = Sequential()

model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(18))

In [275]:

# For each example the model returns a vector of "logits" or "log-odds" scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.19444829,  0.43486935,  0.18828948, -0.18671325,  0.37026516,
        -0.08196621,  0.16913664,  0.06592947, -0.30675662,  0.35159796,
        -0.74065477, -0.12359548,  0.10989833,  0.05565842,  0.336009  ,
        -0.5057974 , -0.42964074,  0.19099417]], dtype=float32)

In [276]:
# The tf.nn.softmax function converts these logits to "probabilities" for each class:
tf.nn.softmax(predictions).numpy()

array([[0.0640201 , 0.08141978, 0.06362703, 0.04373005, 0.07632603,
        0.04855915, 0.06241999, 0.05629909, 0.0387834 , 0.07491446,
        0.0251308 , 0.04657917, 0.05882972, 0.0557238 , 0.07375567,
        0.03178363, 0.03429873, 0.06379935]], dtype=float32)

In [277]:
# The losses.SparseCategoricalCrossentropy loss takes a vector of logits and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [278]:
loss_fn(y_train[:1], predictions).numpy()

3.0249724

In [279]:
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

In [280]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3038 - accuracy: 0.9108
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1435 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1075 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0887 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0737 - accuracy: 0.9774


In [281]:
# The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0788 - accuracy: 0.9757 - 608ms/epoch - 2ms/step


[0.07877697050571442, 0.9757000207901001]

The image classifier is now trained to ~98% accuracy on this dataset. 

In [282]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([
                                         model, 
                                         tf.keras.layers.Softmax()
])

In [283]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 18), dtype=float32, numpy=
array([[2.30761206e-08, 2.00025116e-08, 7.36060065e-06, 3.88342996e-05,
        2.68860433e-12, 5.76888439e-08, 2.86299542e-14, 9.99953628e-01,
        6.64138966e-08, 4.53253399e-08, 5.46443723e-14, 8.47634544e-14,
        3.49449948e-14, 3.74456224e-14, 5.49688502e-14, 6.01817460e-15,
        3.39363242e-14, 8.78346061e-14],
       [2.60258393e-08, 1.12737162e-05, 9.99981165e-01, 4.23698339e-06,
        2.50615609e-13, 1.30428202e-06, 1.40509997e-07, 4.15454644e-13,
        1.81178882e-06, 1.20099758e-13, 1.15054539e-15, 4.32706411e-16,
        1.79816963e-15, 1.13108005e-15, 9.23358324e-15, 1.35604120e-15,
        6.97665463e-16, 1.20107419e-15],
       [1.19878067e-07, 9.98839796e-01, 9.89442342e-05, 7.06095170e-06,
        7.03213882e-05, 6.69019391e-06, 5.91128173e-06, 7.27035222e-04,
        2.43935501e-04, 2.14377934e-07, 2.66853895e-09, 5.69975178e-10,
        1.98523176e-09, 3.20882543e-09, 3.82505050e-09, 4.29617675e-09,
     